version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v12d
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:V10d
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:V10d
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:v10d
