version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v5d
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:V5d
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:V5d
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
