version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v11d
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:V9d
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:V9d
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:v9d
